---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-dev

namePrefix: dev-

resources:
  - ../../base

patches:
  - path: replica-patch.yml
  - path: image-patch.yml
  - path: ingress-patch.yml

configMapGenerator:
  - name: devops-app-config
    behavior: merge
    literals:
      - FLASK_ENV=development
      - LOG_LEVEL=DEBUG