cat > overlays/prod/kustomization.yaml << 'EOF'
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-prod

namePrefix: prod-

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: image-patch.yaml
  - path: ingress-patch.yaml
  - path: resources-patch.yaml

configMapGenerator:
  - name: devops-app-config
    behavior: merge
    literals:
      - FLASK_ENV=production
      - LOG_LEVEL=WARNING
---
EOF
