---
name: Helm CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  helm:
    name: Helm Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Set kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Helm lint
        run: helm lint helm/devops-app

      - name: Helm template
        run: helm template devops-app helm/devops-app > rendered.yaml

      - name: Validate manifests with kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          ./kubeconform -strict -summary rendered.yaml

      
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            ignore: |
              helm/devops-app/templates/*
            rules:
              line-length:
                max: 120
