---
name: Helm CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  helm:
    name: Helm Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Helm lint
        run: helm lint helm/devops-app

      - name: Helm template (render)
        run: helm template devops-app helm/devops-app > rendered.yaml

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Validate Kubernetes manifests
        run: kubectl apply --dry-run=client --validate=false -f rendered.yaml

  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            ignore: |
              helm/devops-app/templates/*
            rules:
              line-length:
                max: 120
